Revert "ANDROID: selinux: modify RTM_GETNEIGH{TBL}"
 An error occurs when compiling lineageos-19.1

../../../../../../kernel/oneplus/sm8150/security/selinux/nlmsgtab.c:227:27: error: use of undeclared identifier 'NETLINK_ROUTE_SOCKET__NLMSG_GETNEIGH'
                nlmsg_set_perm_for_type(NETLINK_ROUTE_SOCKET__NLMSG_GETNEIGH,
                                        ^
../../../../../../kernel/oneplus/sm8150/security/selinux/nlmsgtab.c:229:27: error: use of undeclared identifier 'NETLINK_ROUTE_SOCKET__NLMSG_GETNEIGH'
                nlmsg_set_perm_for_type(NETLINK_ROUTE_SOCKET__NLMSG_GETNEIGH,
                                        ^

This reverts commit 31b8e07de86a8186852bb68a940002934cc2a3b9.